<?php

/**
 * Implementation of hook_ctools_plugin_api().
 *
 * @param $module
 * @param $api
 *
 * @return array
 */
function panels_printpdf_ctools_plugin_api( $module, $api ) {
  if ($module == 'panels' && $api == 'pipelines') {
    return array(
      'version' => 1,
      'path' => drupal_get_path('module', 'panels_printpdf') . '/plugins',
    );
  }
}

/**
 * Implements hook_ctools_plugin_directory().
 *
 * @param $module
 * @param $plugin
 *
 * @return string
 */
function panels_printpdf_ctools_plugin_directory($module, $plugin) {
  if ($module == 'page_manager' || $module == 'panels') {
    return 'plugins/' . $plugin;
  }
}

/**
 * Implements hook_default_panels_renderer_pipeline().
 */
function panels_printpdf_default_panels_renderer_pipeline() {
  $pipelines = array();

  $pipeline = new stdClass;
  $pipeline->disabled = FALSE; /* Edit this to true to make a default pipeline disabled initially */
  $pipeline->api_version = 1;
  $pipeline->name = 'printpdf';
  $pipeline->admin_title = t('Print PDF');
  $pipeline->admin_description = t('Renders a panel as a PDF. Requires print_pdf module.');
  $pipeline->weight = 0;
  $pipeline->settings = array(
    'renderers' => array(
      0 => array(
        'access' => array(),
        'renderer' => 'printpdf',
        'options' => array(),
      ),
    ),
  );
  $pipelines[$pipeline->name] = $pipeline;

  return $pipelines;
}
